### ISSUE TITLE
HUD Scale To-Do

### ISSUE THREAD

**Issue by SonicFreak94** [sonicretro/sadx-mod-loader#8]
Sprites:
- [ ] Sky Chase reticle

The Sky Chase reticle will probably require actual gameplay changes, so it's most likely better suited to SADX Fixed Edition. We'll see though.

Non-Sprite:
- [ ] Big's Fishing Line Tension (surrounding elements are sprites)
- [ ] Title Cards
- [ ] Menus (e.g main menu, character select)
- [ ] Subtitles
- [ ] Map (from pause menu)
- [ ] Mission screen (from pause menu)
- [ ] Chao HUD (X/Y pick up/pet)
- [ ] Chao Stats
- [ ] Chao Menus (departure, black market, race)
- [ ] Credits

**Comment by Zetchzie** [comment]
This has to be the most important feature to me lol

Hope it gets updated more soon

**Comment by PiKeyAr** [comment]
Recently I came across a comment stating that playing at higher resolutions affects score calculation in Sky Chase. Apparently getting a high score (needed for emblems) is much easier at lower resolutions. Also, according to that comment, some enemies don't fire at 1080p.
[Original comment here](https://steamcommunity.com/app/71250/discussions/0/613938693207081231/).

**Comment by Zetchzie** [comment]
Does Not affect score but it gives you ALLOT more room to move around in making the minigame a hassle

**Comment by PiKeyAr** [comment]
sub_6436B0 - tutorial background

**Comment by RinMaru** [comment]
Just need chao stuff and blackmarket and ill be forever happy

**Comment by PiKeyAr** [comment]
sub_7493B0 - Chao Race entry menu

**Comment by PiKeyAr** [comment]
Not sure if this is useful, but it's possible to make the game play higher resolution videos or scale lower resolution videos properly. Here's how I got it to play a 1280x960 video.

In the array of VideoData structures at 0x010DB8B0 edit the Width and Height value for the needed video to match those of the actual video. This will make the game scale the video properly, which is enough for videos smaller than 640x480. For bigger videos you also need to patch the function that scales the texture used to display the video. In sub_513850 there's a structure whose coordinates and UVs are adjusted using hardcoded dimensions of 640x480.

There are two 2-byte ints used to set the TEXANIM struct's X and Y coordinates: X at 0x513918 and Y at 0x513921. So to scale it to 1280x960 I wrote 00 05 to 0x513918 and C0 03 to 0x513921. Then I patched the floats used to calculate the texture's UVs:
WriteData((float**)0x51392C, &VideoSize_X);
WriteData((float**)0x513950, &VideoSize_Y);

Finally, I also had to patch dword_10F1D68 to be larger than its default value of 1024 (1280 seems to work), obviously this is a dumb way to do it and it's better to rewrite sub_513850 to use a bigger value. I think it's involved in memory allocation, but I'm not familiar enough with this stuff. Also the above things need to be checked in other resolutions because I used a video that matched my SADX window size.

**Comment by cheatfreak47** [comment]
Missed thingie: Adventure Field Emblem Counters appear to not scale

**Comment by SonicFreak94** [comment]
fdf557d5a93aa670c659764a9acf1e42e7ebe690 fixes the adventure field emblem counter

**Comment by PiKeyAr** [comment]
`sub_642790` - Character recap screen text
```
v10 = (double)v5 - 240.0 + VerticalStretch * 240.0;
v11 = (double)v6 - 320.0 + HorizontalStretch * 320.0;
sub_6424A0((int)(v4 + 36), -1, 64.0, v11, v10, 20.0, v9, v8);
```

**Comment by PiKeyAr** [comment]
Looks like the tutorials break with the default "Stretch" option for backgrounds enabled
Screenshot (no mods):
![image](https://user-images.githubusercontent.com/23312549/39663104-ee49e56e-50a7-11e8-86ef-8c7dc17f04a0.png)

**Comment by cheatfreak47** [comment]
Funny I was actually just about to post about this myself.
Can confirm, someone reported this issue to me in the BetterSADX comments, with this screenshot:
https://steamcommunity.com/sharedfiles/filedetails/?id=1378184911

**Comment by PiKeyAr** [comment]
Float at 0x0070142D is screen scale for the Game Gear emulator.

**Comment by michael-fadely** [comment]
Would somebody mind validating that the posted addresses/UI elements still need fixing? I have the free time, so I'd like to tackle these ASAP.

**Comment by cheatfreak47** [comment]
I'd imagine a lot of them still do
All the Game Gear stuff for example, I think lots of chao garden stuff needs looked at too. Really just open the game and you'll see, tons of stuff needs work for scaling correctly.

**Comment by michael-fadely** [comment]
That much is obvious. What I was asking for was specifically for validation of the posted addresses.

**Comment by michael-fadely** [comment]
> 
> 
> Float at 0x0070142D is screen scale for the Game Gear emulator.

This is used as part of a larger structure which I would like to understand first.

**Comment by michael-fadely** [comment]
> 
> 
> Looks like the tutorials break with the default "Stretch" option for backgrounds enabled
> Screenshot (no mods):
> [snip]

I've identified the issue here. There are user interface elements that are scaling as they *technically should* since HUD scaling is still enabled, but that ought not in this context

In debug builds of the mod loader, pressing the Dreamcast Z button will disable the scaling. Without holding the debug button:
![image](https://user-images.githubusercontent.com/920569/72232500-c249f680-357e-11ea-838d-8079138e6ced.png)

While holding the debug button:
![image](https://user-images.githubusercontent.com/920569/72232508-c83fd780-357e-11ea-9b80-1379a6bbb357.png)

I will figure out a solution.

**Comment by PiKeyAr** [comment]
Thought I should mention this here. SADX title screen is currently stretched at aspect ratios other than 4:3.
![image](https://user-images.githubusercontent.com/23312549/72659915-ea67a880-3a09-11ea-8558-62edaa772b10.png)

**Comment by michael-fadely** [comment]
Title screen fixed.

**Comment by PiKeyAr** [comment]
![image](https://user-images.githubusercontent.com/23312549/73136142-a457b800-408d-11ea-80a2-09ebc387bb57.png)
737BD0 - Chao stat panel

**Comment by PiKeyAr** [comment]
![image](https://user-images.githubusercontent.com/23312549/73136228-a3735600-408e-11ea-925a-060cf9973176.png)
728A40 - sets up Black Market UI
725420 - Draws menu header
7256C0 - Draws text
726760 - Draws buttons
7270E0 - Draws item list
725A30 - Draws item preview

**Comment by michael-fadely** [comment]
> 
> 
> 71B210 - Chao button prompts

Scaling for this has been sitting in the mod loader for quite some time, but it has been disabled because the text rendering in this context is not reverse engineered and becomes invisible.

**Comment by PiKeyAr** [comment]
Re: Game Gear emulator, I think the structure in question might be this:
```
struct __cppobj TAdvertiseBase : TObject
{
  TAdvertiseBase::AdvertiseBaseParam Param;
  NJS_POINT2 Center;
  float Spd;
  float Radian;
  float DispScaleX;
  float DispScaleY;
  float Current;
  __int16 Triangle;
  __int16 TriangleUp;
  int Trans;
  NJS_POINT2 Offset;
  int Timer;
};
```

**Comment by cheatfreak47** [comment]
I don't think the animated HUD thing for Big the Cat when he catches a fish, ya know, where it adds the weight to your weight indicator is scaled quite properly.

**Comment by michael-fadely** [comment]
example?

**Comment by cheatfreak47** [comment]
Sure. The game is running at 4K here.

On Catch at 4K:
https://gfycat.com/VictoriousPleasedDipper

On Catch 640x480 no scaling enabled:
https://gfycat.com/WhimsicalLeanBoar

This also seems to be the case for when you fail to catch something.

On Fail at 4K:
![tiny_onfishfail](https://user-images.githubusercontent.com/7818664/78071190-0c1acf80-736b-11ea-9d45-88342d72831d.png)

**Comment by PiKeyAr** [comment]
Some remaining issues with Chao HUD scaling.
Chao emotion balls and Chaos Chao sparks are positioned incorrectly. Also, the sparks are too big while the emotion balls are slightly too small I think.
![image](https://user-images.githubusercontent.com/23312549/126031513-2b4dea59-4bcd-4a9c-8675-a60f51514ab6.png)

The Sonic Team homepage prompt isn't scaled:
![image](https://user-images.githubusercontent.com/23312549/126031546-ed90a25e-92ca-4be9-8b92-3a134c4b68d3.png)

Minor issue, but I think it would look less awkward if the sliding elements in Chao Race Entry menu had their initial position adjusted to be off screen at aspect ratios other than 4:3. This is how they currently look when the screen fades in at 16:9.
![image](https://user-images.githubusercontent.com/23312549/126032263-495b9543-86c3-4008-b965-a5a26b26dff2.png)

**Comment by PiKeyAr** [comment]
Sonic Team homepage screen fixed.
