### ISSUE TITLE
Window Resize To-Do

### ISSUE THREAD

**Issue by SonicFreak94** [sonicretro/sadx-mod-loader#9]
For the window-resize branch:
- [x] Handle device lost (will allow minimizing, fullscreen toggle, and long-standing alt+tab crash)
- [x] Fullscreen toggle (only works if windowed at startup)
- [x] Fullscreen toggle (fullscreen at startup)
- [x] Make fullscreen toggle borderless window-aware
- [x] Correct window size on startup
- [x] Don't change internal resolution if custom internal resolution is set
- [x] Toggle for window resizing

**Comment by SonicFreak94** [comment]
merged
